/**
 * Excursion Detail Block
 * Reads excursion data embedded in the page by the feed pipeline.
 * Each page is generated with data fields as <p> elements inside the block.
 *
 * Field order (as generated by pipeline):
 * [0] id, [1] name, [2] portName, [3] destinationName, [4] activityLevel,
 * [5] collectionType, [6] duration, [7] priceLevel, [8] currency,
 * [9] wheelChairAccessible, [10] longDescription
 *
 * @param {Element} block The block element
 */
export default async function decorate(block) {
  const row = block.querySelector(':scope > div > div');
  if (!row) return;

  const fields = [...row.querySelectorAll('p')];
  if (fields.length < 11) {
    block.textContent = 'Excursion data incomplete.';
    return;
  }

  const data = {
    id: fields[0].textContent.trim(),
    name: fields[1].textContent.trim(),
    portName: fields[2].textContent.trim(),
    destinationName: fields[3].textContent.trim(),
    activityLevel: fields[4].textContent.trim(),
    collectionType: fields[5].textContent.trim(),
    duration: fields[6].textContent.trim(),
    priceLevel: fields[7].textContent.trim(),
    currency: fields[8].textContent.trim(),
    wheelChairAccessible: fields[9].textContent.trim() === 'true',
    longDescription: fields[10].textContent.trim(),
  };

  const destinationSlug = data.destinationName.toLowerCase().replace(/\s+/g, '-');

  block.innerHTML = `
    <div class="excursion-detail-content">
      <nav class="excursion-detail-breadcrumb" aria-label="Breadcrumb">
        <a href="/cruise-destinations">Destinations</a> &rsaquo;
        <a href="/cruise-destinations/${destinationSlug}">${data.destinationName}</a> &rsaquo;
        <span>${data.portName}</span> &rsaquo;
        <span>${data.name}</span>
      </nav>
      <h1>${data.name}</h1>
      <div class="excursion-detail-meta">
        <span class="excursion-detail-badge">${data.collectionType.replace(/_/g, ' ')}</span>
        <span class="excursion-detail-badge">${data.activityLevel.replace(/_/g, ' ')}</span>
        ${data.wheelChairAccessible ? '<span class="excursion-detail-badge">♿ Accessible</span>' : ''}
      </div>
      <div class="excursion-detail-info">
        <div class="excursion-detail-info-item">
          <strong>Duration</strong>
          <span>${data.duration}</span>
        </div>
        <div class="excursion-detail-info-item">
          <strong>Price</strong>
          <span>From $${data.priceLevel} ${data.currency}</span>
        </div>
        <div class="excursion-detail-info-item">
          <strong>Port</strong>
          <span>${data.portName}</span>
        </div>
        <div class="excursion-detail-info-item">
          <strong>Type</strong>
          <span>Shore Excursion</span>
        </div>
      </div>
      <div class="excursion-detail-description">
        <h2>About This Excursion</h2>
        <p>${data.longDescription}</p>
      </div>
    </div>
  `;
}
