/**
 * Cruise Detail Block
 * Reads cruise data embedded in the page by the feed pipeline.
 *
 * Field order (as generated by pipeline):
 * [0] cruiseId, [1] itineraryId, [2] name, [3] nightName, [4] shipName,
 * [5] duration, [6] departDate, [7] arrivalDate, [8] departPortId,
 * [9] arrivalPortId, [10] soldOut, [11] portList
 *
 * @param {Element} block The block element
 */
export default async function decorate(block) {
  const row = block.querySelector(':scope > div > div');
  if (!row) return;

  const fields = [...row.querySelectorAll('p')];
  if (fields.length < 12) {
    block.textContent = 'Cruise data incomplete.';
    return;
  }

  const data = {
    cruiseId: fields[0].textContent.trim(),
    itineraryId: fields[1].textContent.trim(),
    name: fields[2].textContent.trim(),
    nightName: fields[3].textContent.trim(),
    shipName: fields[4].textContent.trim(),
    duration: fields[5].textContent.trim(),
    departDate: fields[6].textContent.trim(),
    arrivalDate: fields[7].textContent.trim(),
    departPort: fields[8].textContent.trim(),
    arrivalPort: fields[9].textContent.trim(),
    soldOut: fields[10].textContent.trim() === 'true',
    ports: fields[11].textContent.trim(),
  };

  const formatDate = (dateStr) => {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  block.innerHTML = `
    <div class="cruise-detail-content">
      <nav class="cruise-detail-breadcrumb" aria-label="Breadcrumb">
        <a href="/find-a-cruise">Find a Cruise</a> &rsaquo;
        <span>${data.name}</span>
      </nav>
      <h1>${data.nightName}</h1>
      ${data.soldOut ? '<span class="cruise-detail-sold-out">Sold Out</span>' : ''}
      <div class="cruise-detail-meta">
        <span class="cruise-detail-badge">${data.shipName}</span>
        <span class="cruise-detail-badge">${data.duration} nights</span>
      </div>
      <div class="cruise-detail-info">
        <div class="cruise-detail-info-item">
          <strong>Departure</strong>
          <span>${formatDate(data.departDate)} from ${data.departPort}</span>
        </div>
        <div class="cruise-detail-info-item">
          <strong>Arrival</strong>
          <span>${formatDate(data.arrivalDate)} at ${data.arrivalPort}</span>
        </div>
        <div class="cruise-detail-info-item">
          <strong>Ship</strong>
          <span>${data.shipName}</span>
        </div>
        <div class="cruise-detail-info-item">
          <strong>Duration</strong>
          <span>${data.duration} nights</span>
        </div>
      </div>
      <div class="cruise-detail-ports">
        <h2>Ports of Call</h2>
        <div class="cruise-detail-port-list">
          ${data.ports.split(', ').map((port) => `<span class="cruise-detail-port-chip">${port}</span>`).join('')}
        </div>
      </div>
    </div>
  `;
}
